version = 0.1

[default.deploy.parameters]
stack_name = "crud-api-nodejs"
resolve_s3 = true
s3_prefix = "crud-api-nodejs"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
